import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { IO } from "../io.js";
import { buildEnvContent, ensureGitignore } from "../env.js";

export interface InitAnswers {
  google?: { apiKey: string };
  internal?: { csvPath: string };
  strategy: "first-success" | "merge";
}

const isYes = (answer: string): boolean => /^y(es)?$/i.test(answer.trim());

/** 답변 → .env 변수 맵 */
export function buildEnvVars(answers: InitAnswers): Record<string, string> {
  const vars: Record<string, string> = {};
  if (answers.google) vars.GOOGLE_MAPS_API_KEY = answers.google.apiKey;
  if (answers.internal) vars.GEOWIRE_INTERNAL_CSV = answers.internal.csvPath;
  return vars;
}

/** 답변 → geowire.config.yaml 텍스트 (평문 키 대신 ${ENV} 참조 사용) */
export function buildConfigYaml(answers: InitAnswers): string {
  const lines = [
    "# GeoWire config — generated by `geowire init`",
    "providers:",
    "  nominatim: { enabled: true }",
  ];
  if (answers.google) lines.push("  google: { enabled: true, apiKey: ${GOOGLE_MAPS_API_KEY} }");
  if (answers.internal) {
    lines.push(`  internal: { enabled: true, source: ${answers.internal.csvPath}, priority: 100 }`);
  }
  lines.push("routing:", `  defaultStrategy: ${answers.strategy}`);
  return `${lines.join("\n")}\n`;
}

export interface InitDeps {
  /** 프롬프트 질문 → 사용자 응답 (테스트에서 주입) */
  ask: (question: string) => Promise<string>;
  cwd: string;
  io: IO;
}

/**
 * 대화형 설정 마법사 (설계 §9 `geowire init`).
 * provider 선택 → 키 입력 → `.env` + `geowire.config.yaml` 생성 → `.gitignore`에 `.env` 추가.
 */
export async function runInit(deps: InitDeps): Promise<number> {
  const { ask, cwd, io } = deps;
  io.out("GeoWire setup wizard");
  io.out("nominatim (OpenStreetMap) is always enabled — no API key required.\n");

  const answers: InitAnswers = { strategy: "first-success" };

  if (isYes(await ask("Enable Google Maps? (needs an API key) [y/N]: "))) {
    const key = (await ask("  Google Maps API key: ")).trim();
    if (key) answers.google = { apiKey: key };
  }

  if (isYes(await ask("Add your own places from a CSV file? [y/N]: "))) {
    const path = (await ask("  CSV file path [./my-places.csv]: ")).trim();
    answers.internal = { csvPath: path || "./my-places.csv" };
  }

  if (answers.google || answers.internal) {
    if (isYes(await ask("Merge results across providers (dedup)? [y/N]: "))) {
      answers.strategy = "merge";
    }
  }

  const vars = buildEnvVars(answers);
  if (Object.keys(vars).length > 0) {
    const envPath = join(cwd, ".env");
    writeFileSync(envPath, buildEnvContent(vars), "utf8");
    io.out(`\n✓ wrote ${envPath}`);
    if (ensureGitignore(join(cwd, ".gitignore"), ".env")) {
      io.out("✓ added .env to .gitignore");
    }
  }

  const configPath = join(cwd, "geowire.config.yaml");
  writeFileSync(configPath, buildConfigYaml(answers), "utf8");
  io.out(`✓ wrote ${configPath}\n`);

  io.out("Next steps:");
  io.out("  geowire test                    # verify provider connections");
  io.out('  geowire search "coffee near me" # one-shot search');
  io.out("  geowire                         # start the server");
  return 0;
}
